server:
  port: 8010
  servlet:
    context-path: /
spring:
  application:
    # 指定注册到eureka server上的服务名称
    name: shopping-center-user
  profiles:
    active: dev
  redis:
    host: 129.204.75.83
    port: 6379
    # 密码 没有则可以不填
    requirePass: 123456
    # 如果使用的jedis 则将lettuce改成jedis即可
    lettuce:
      pool:
        # 最大活跃链接数 默认8
        max-active: 8
        # 最大空闲连接数 默认8
        max-idle: 8
        # 最小空闲连接数 默认0
        min-idle: 0

eureka:
  client:
    service-url:
      # 指定eureka server通信地址，注意/eureka/小尾巴不能少
      defaultZone: http://localhost:8761/eureka/
  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    prefer-ip-address: true

logging:
  level:
    study.user.feign.UserFeignClient: debug


feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: 'hystrix.stream'

