server:
  port: 8040
spring:
  application:
    name: shopping-center-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    shopping-center-member: /apigateway/**
  #统一入口为上面的配置,其它入口忽略
  ignored-patterns: /*-service/**
  #处理http请求头为空的问题，
  sensitive-headers:

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
#自定义路由映射